version: '3.8'

services:
  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  web:
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 